service: listen-list

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-domain-manager

custom:
  wsgi:
    app: api.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: non-linux

  customDomain:
    domainName: 'api.listenlist.io'
    certificateName: '*.listenlist.io'
    stage: ${self:provider.stage}
    # basePath: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'alpha'}
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true

functions:
  app:
    handler: wsgi_handler.handler
    package:
      exclude:
        - tests/**
        - schema/**
        - .vscode/**
        - .pytest_cache/**
        - .circleci/**
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'