version: 2.1

workflows:
  pytest:
    jobs:
      - test:
          context: AWS

jobs:
  test:
    working_directory: ~/repo

    docker:
      - image: circleci/python:3.8

    steps:
      # Get the code
      - checkout
      
      - restore_cache:
          key: -v3-{{ checksum "Pipfile" }}

      # Install the dependencies
      - run: 
          name: "Install Dependencies"
          command: |
            pipenv install

      - save_cache:
          key: -v3-{{ checksum "Pipfile" }}
          paths:
            - ".venv"

      # Run pytest
      - run:
          name: "Run PyTest"
          command: |
            pipenv run pytest
      