version: 2.1

workflows:
  # test:
  #   jobs:
  #     - test:
  #         context: AWS
  release:
    jobs:
      - release:
          context: Github

jobs:
  test:
    working_directory: ~/repo

    docker:
      - image: circleci/python:3.8

    steps:
      # Get the code
      - checkout
      
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-

      # Install the dependencies
      - run: 
          name: "Install Dependencies"
          command: pipenv sync --dev

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

      # Run pytest
      - run:
          name: "Run PyTest"
          command: |
            pipenv run pytest

  release:
    docker:
      - image: cimg/node:15.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package-lock.json" }}
            - cache-
      - run:
          name:  "Install NPM"
          command: npm install
      - run:
          name:  "Semantic Release"
          command: npx semantic-release
      - save_cache:
          key: cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.local
            - ~/.cache