version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: AWS # has an env var called AWS_PROFILE

jobs:
  build:
    docker:
      - image: circleci/python:3.8
        auth:
    steps:
      - checkout
      - run: 
          name: "echo an env var that is part of our context"
          command: |
            echo $AWS_PROFILE