version: 2.1

workflows:
  test:
    jobs:
      - test:
          context: AWS
      - release:
          context: Github
  release:
    jobs:
      - release:
          context: Github

jobs:
  test:
    working_directory: ~/repo

    docker:
      - image: circleci/python:3.8

    steps:
      # Get the code
      - checkout
      
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-

      # Install the dependencies
      - run: 
          name: "Install Dependencies"
          command: pipenv sync --dev

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

      # Run pytest
      - run:
          name: "Run PyTest"
          command: |
            pipenv run pytest

  release:
    docker:
      - image: cimg/node:15.6.0
    steps:
      - checkout
      - run: npm install
      # Run optional required steps before releasing
      # - run: npm run build-script
      - run: npx semantic-release