version: 2.1

workflows:
  pytest:
    jobs:
      - build:
          context: AWS # has an env var called AWS_PROFILE

jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/python:3.8

    steps:
      # Get the code
      - checkout

      # Install the dependencies
      - run: 
          name: "Install Dependencies"
          command: |
            pipenv install

      # Run pytest
      - run:
          name: "Run PyTest"
          command: |
            pipenv run pytest -v -k keys
      